# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy ASP.Net Core app to Azure Web App - urlShortenerBackend

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    env:
        CONNECTION_STRING: ${{ secrets.CONNECTION_STRING }}
        DATABASE_NAME: ${{ secrets.DATABASE_NAME }}
        COLLECTION_NAME: ${{ secrets.COLLECTION_NAME }}

    steps:
      - uses: actions/checkout@v2

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '7.x'
          include-prerelease: true

      - name: Build with dotnet
        run: dotnet build --configuration Release

      - name: dotnet publish
        run: dotnet publish -c Release -o ${{env.DOTNET_ROOT}}/myapp
        
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: .net-app
          path: ${{env.DOTNET_ROOT}}/myapp

      - name: test the environments
        run: 
          echo $CONNECTION_STRING
          echo $DATABASE_NAME
          echo $COLLECTION_NAME
          echo $files

  deploy:
    runs-on: windows-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: .net-app

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'urlShortenerBackend'
          slot-name: 'Production'
          publish-profile: "${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_0042B6DD05434AFAB0682A076D07EB7F }}"
          package: .
